name: build-wasm
on:
  push:
    branches:
      - '**'
  pull_request:

jobs:
  build-wasm:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14
      - name: Build WebAssembly
        run: |
          mkdir -p build-wasm
          cd build-wasm
          emcmake cmake ..
          emmake make -j2
